spring:
  application:
    name: spring-data

  datasource:
    url: jdbc:postgresql://${AUTH_SERVICE_POSTGRES_HOST}:5432/${AUTH_SERVICE_POSTGRES_DATABASE}
    username: ${AUTH_SERVICE_POSTGRES_USERNAME}
    password: ${AUTH_SERVICE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: ${AUTH_SERVICE_HTTP_PORT}
  error:
    include-message: always
    include-binding-errors: always
