spring:
  application:
    name: spring-data

  datasource:
    url: jdbc:postgresql://${CATALOG_SERVICE_POSTGRES_HOST}:${CATALOG_SERVICE_POSTGRES_PORT}/${CATALOG_SERVICE_POSTGRES_DATABASE}
    username: ${CATALOG_SERVICE_POSTGRES_USERNAME}
    password: ${CATALOG_SERVICE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8001
  error:
    include-message: always
    include-binding-errors: always

config:
  stock-service-host: ${STOCK_SERVICE_HOST}
  stock-service-port: ${STOCK_SERVICE_PORT}
  secret-key: ${STOCK_SERVICE_SECRET_KEY}