spring:
  application:
    name: spring-data

  datasource:
    url: jdbc:postgresql://${STOCK_SERVICE_POSTGRES_HOST}:${STOCK_SERVICE_POSTGRES_PORT}/${STOCK_SERVICE_POSTGRES_DATABASE}
    username: ${STOCK_SERVICE_POSTGRES_USERNAME}
    password: ${STOCK_SERVICE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8005
  error:
    include-message: always
    include-binding-errors: always

config:
  min_stock_alert: ${STOCK_SERVICE_MIN_STOCK_ALERT}
  secret-key: ${STOCK_SERVICE_SECRET_KEY}
