spring:
  application:
    name: spring-data

  datasource:
    url: jdbc:postgresql://${PAYMENT_SERVICE_POSTGRES_HOST}:${PAYMENT_SERVICE_POSTGRES_PORT}/${PAYMENT_SERVICE_POSTGRES_DATABASE}
    username: ${PAYMENT_SERVICE_POSTGRES_USERNAME}
    password: ${PAYMENT_SERVICE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8003
  error:
    include-message: always
    include-binding-errors: always
