spring:
  application:
    name: spring-data

  datasource:
    url: jdbc:postgresql://${PAYMENT_SERVICE_POSTGRES_HOST}:${PAYMENT_SERVICE_POSTGRES_PORT}/${PAYMENT_SERVICE_POSTGRES_DATABASE}
    username: ${PAYMENT_SERVICE_POSTGRES_USERNAME}
    password: ${PAYMENT_SERVICE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8003
  error:
    include-message: always
    include-binding-errors: always

config:
  bank-service-host: ${BANK_SERVICE_HOST}
  bank-service-port: ${BANK_SERVICE_PORT}
  credit-card-service-host: ${CREDIT_CARD_SERVICE_HOST}
  credit-card-service-port: ${CREDIT_CARD_SERVICE_PORT}
  shipment-service-host: ${SHIPMENT_SERVICE_HOST}
  shipment-service-port: ${SHIPMENT_SERVICE_PORT}
  order-service-host: ${ORDER_SERVICE_HOST}
  order-service-port: ${ORDER_SERVICE_PORT}
  auth-service-host: ${AUTH_SERVICE_HOST}
  auth-service-port: ${AUTH_SERVICE_PORT}
  secret-key: ${SECRET_KEY}