spring:
  application:
    name: spring-data

  datasource:
    url: jdbc:postgresql://${ORDER_SERVICE_POSTGRES_HOST}:${ORDER_SERVICE_POSTGRES_PORT}/${ORDER_SERVICE_POSTGRES_DATABASE}
    username: ${ORDER_SERVICE_POSTGRES_USERNAME}
    password: ${ORDER_SERVICE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true

server:
  port: 8002
  error:
    include-message: always
    include-binding-errors: always
