apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-db: YXV0aC1zZXJ2aWNl
  postgres-user: YXV0aC1zZXJ2aWNlLXVzZXI=
  postgres-password: YXV0aC1zZXJ2aWNlLXBhc3N3b3Jk
