apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: auth-postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: auth-postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-service
spec:
  selector:
    app: auth-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-auth
  labels:
    app: ecommerce-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-auth
  template:
    metadata:
      labels:
        app: ecommerce-auth
    spec:
      containers:
        - name: ecommerce-auth
          image: nodirshox/ecommerce-auth
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: auth-postgres-db
            - name: AUTH_SERVICE_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: AUTH_SERVICE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: AUTH_SERVICE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: auth_database_url
            - name: AUTH_SERVICE_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-auth-service
spec:
  selector:
    app: ecommerce-auth
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000