apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-bank
  labels:
    app: ecommerce-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-bank
  template:
    metadata:
      labels:
        app: ecommerce-bank
    spec:
      containers:
        - name: ecommerce-bank
          image: nodirshox/ecommerce-bank
          ports:
            - containerPort: 8007
          env:
            - name: BANK_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: bank-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-bank-service
spec:
  selector:
    app: ecommerce-bank
  ports:
    - protocol: TCP
      port: 8007
      targetPort: 8007
