apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-card
  labels:
    app: ecommerce-card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-card
  template:
    metadata:
      labels:
        app: ecommerce-card
    spec:
      containers:
        - name: ecommerce-card
          image: nodirshox/ecommerce-card-service
          ports:
            - containerPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-card-service
spec:
  selector:
    app: ecommerce-card
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
