apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-catalog
  labels:
    app: ecommerce-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-catalog
  template:
    metadata:
      labels:
        app: ecommerce-catalog
    spec:
      containers:
        - name: ecommerce-catalog
          image: nodirshox/ecommerce-catalog
          ports:
            - containerPort: 8001
          env:
            - name: CATALOG_SERVICE_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: CATALOG_SERVICE_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: CATALOG_SERVICE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: CATALOG_SERVICE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url
            - name: CATALOG_SERVICE_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
            - name: STOCK_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: stock_service_host
            - name: STOCK_SERVICE_PORT
              value: "8005"

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-catalog-service
spec:
  selector:
    app: ecommerce-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001