apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-postgres
  template:
    metadata:
      labels:
        app: catalog-postgres
    spec:
      containers:
        - name: catalog-postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: catalog-postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-postgres-service
spec:
  selector:
    app: catalog-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-catalog
  labels:
    app: ecommerce-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-catalog
  template:
    metadata:
      labels:
        app: ecommerce-catalog
    spec:
      containers:
        - name: ecommerce-catalog
          image: nodirshox/ecommerce-catalog
          ports:
            - containerPort: 8000
          env:
            - name: CATALOG_SERVICE_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: catalog-postgres-db
            - name: CATALOG_SERVICE_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: CATALOG_SERVICE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: CATALOG_SERVICE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: catalog_database_url
            - name: CATALOG_SERVICE_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-catalog-service
spec:
  selector:
    app: ecommerce-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001