apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-payment
  labels:
    app: ecommerce-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-payment
  template:
    metadata:
      labels:
        app: ecommerce-payment
    spec:
      containers:
        - name: ecommerce-payment
          image: nodirshox/ecommerce-payment
          ports:
            - containerPort: 8003
          env:
            - name: PAYMENT_SERVICE_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: PAYMENT_SERVICE_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: PAYMENT_SERVICE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: PAYMENT_SERVICE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url
            - name: PAYMENT_SERVICE_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
            - name: BANK_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: bank_service_host
            - name: BANK_SERVICE_PORT
              value: "8007"
            - name: CREDIT_CARD_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: card_service_host
            - name: CREDIT_CARD_SERVICE_PORT
              value: "8006"
            - name: SHIPMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: shipping_service_host
            - name: SHIPMENT_SERVICE_PORT
              value: "8004"
            - name: ORDER_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: order_service_host
            - name: ORDER_SERVICE_PORT
              value: "8002"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: header-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-payment-service
spec:
  selector:
    app: ecommerce-payment
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
