apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-shipping
  labels:
    app: ecommerce-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-shipping
  template:
    metadata:
      labels:
        app: ecommerce-shipping
    spec:
      containers:
        - name: ecommerce-shipping
          image: nodirshox/ecommerce-shipping
          ports:
            - containerPort: 8004
          env:
            - name: SHIPPING_SERVICE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: shipping-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-shipping-service
spec:
  selector:
    app: ecommerce-shipping
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
