apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-postgres
  template:
    metadata:
      labels:
        app: stock-postgres
    spec:
      containers:
        - name: stock-postgres
          image: postgres:14.5-alpine3.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: stock-postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: stock-postgres-service
spec:
  selector:
    app: stock-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-stock
  labels:
    app: ecommerce-stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-stock
  template:
    metadata:
      labels:
        app: ecommerce-stock
    spec:
      containers:
        - name: ecommerce-stock
          image: nodirshox/ecommerce-stock
          ports:
            - containerPort: 8005
          env:
            - name: STOCK_SERVICE_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: stock-postgres-db
            - name: STOCK_SERVICE_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: STOCK_SERVICE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: STOCK_SERVICE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: stock_database_url
            - name: STOCK_SERVICE_POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
            - name: STOCK_SERVICE_MIN_STOCK_ALERT
              value: "50"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-stock-service
spec:
  selector:
    app: ecommerce-stock
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
